"""给菜品表添加了 种类 字段

Revision ID: 69009f39330b
Revises: 
Create Date: 2026-07-14 09:57:39.387638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69009f39330b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dish_img', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=20), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.drop_column('is_finished')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_finished', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('status')
        batch_op.drop_column('total_price')

    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('dish_img')

    # ### end Alembic commands ###
